/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the caller's own profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /** Delete (anonymize) the caller's own account */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /** Claim/change the caller's username and/or edit their display name */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/jobs/nfl/sync-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest the NFL schedule (regular season + postseason) into our tables */
        post: operations["runNflSyncSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/nfl/sync-odds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot spreads for unstarted games in the current NFL week */
        post: operations["runNflSyncOdds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/nfl/sync-scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh live scores/statuses for in-flight NFL games from the provider */
        post: operations["runNflSyncScores"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's leagues (dashboard) */
        get: operations["listMyLeagues"];
        put?: never;
        /** Create a league; the creator becomes a commissioner */
        post: operations["createLeague"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leagues/{leagueId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a league with settings and members (members only) */
        get: operations["getLeague"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        MeResponse: {
            id: string;
            username: components["schemas"]["NullableUsername"];
            displayName: string;
            email: string;
            image: string | null;
        };
        NullableUsername: string | null;
        ErrorResponse: {
            error: string;
            message: string;
        };
        UpdateMeRequest: {
            username?: components["schemas"]["Username"];
            displayName?: components["schemas"]["DisplayName"];
        };
        Username: string;
        DisplayName: string;
        JobRunResponse: {
            job: string;
            /** @enum {string} */
            status: "ok" | "error";
            durationMs: number;
            details?: {
                [key: string]: string | number | boolean;
            };
            message?: string;
        };
        /** @enum {string} */
        WeekType: "regular" | "postseason";
        LeagueResponse: {
            id: string;
            name: components["schemas"]["LeagueName"];
            mode: components["schemas"]["LeagueMode"];
            visibility: components["schemas"]["LeagueVisibility"];
            status: components["schemas"]["LeagueStatus"];
            seasonYear: number;
            settings: components["schemas"]["LeagueSettings"];
            /** Format: date-time */
            startsAt: string | null;
            myRole: components["schemas"]["MemberRole"];
            members: components["schemas"]["LeagueMember"][];
        };
        LeagueName: string;
        /** @enum {string} */
        LeagueMode: "pickem" | "elimination" | "march_madness";
        /** @enum {string} */
        LeagueVisibility: "public" | "private";
        /** @enum {string} */
        LeagueStatus: "active" | "concluded";
        LeagueSettings: components["schemas"]["PickemSettings"] | components["schemas"]["EliminationSettings"] | {
            /** @default 5 */
            maxBracketsPerMember: number;
            /** @enum {string} */
            scoringModel: "standard_doubling";
        } | {
            /** @default 5 */
            maxBracketsPerMember: number;
            /** @enum {string} */
            scoringModel: "custom";
            roundValues: number[];
        };
        PickemSettings: {
            startWeek: components["schemas"]["NflWeekRef"];
            endWeek: components["schemas"]["NflWeekRef"];
            pickType: components["schemas"]["PickType"];
            /** @default 5 */
            picksPerWeek: number;
            pushTieResolution?: components["schemas"]["PickemPushTieResolution"];
        };
        NflWeekRef: {
            /** @enum {string} */
            type: "regular";
            number: number;
        } | {
            /** @enum {string} */
            type: "postseason";
            number: number;
        };
        /** @enum {string} */
        PickType: "straight_up" | "against_the_spread";
        /**
         * @default half_point
         * @enum {string}
         */
        PickemPushTieResolution: "half_point" | "zero_points" | "full_point";
        EliminationSettings: {
            startWeek: {
                /** @enum {string} */
                type: "regular";
                number: number;
            };
            endWeek: {
                /** @enum {string} */
                type: "regular";
                number: number;
            };
            pickType: components["schemas"]["PickType"];
            pushTieResolution?: components["schemas"]["EliminationPushTieResolution"];
        };
        /**
         * @default advance
         * @enum {string}
         */
        EliminationPushTieResolution: "advance" | "eliminate";
        /** @enum {string} */
        MemberRole: "commissioner" | "member";
        LeagueMember: {
            id: string;
            userId: string;
            username: string | null;
            displayName: string;
            image: string | null;
            role: components["schemas"]["MemberRole"];
            /** Format: date-time */
            joinedAt: string;
        };
        CreateLeagueRequest: {
            /** @enum {string} */
            mode: "pickem";
            name: components["schemas"]["LeagueName"];
            visibility: components["schemas"]["LeagueVisibility"];
            settings: components["schemas"]["PickemSettings"];
        } | {
            /** @enum {string} */
            mode: "elimination";
            name: components["schemas"]["LeagueName"];
            visibility: components["schemas"]["LeagueVisibility"];
            settings: components["schemas"]["EliminationSettings"];
        } | {
            /** @enum {string} */
            mode: "march_madness";
            name: components["schemas"]["LeagueName"];
            visibility: components["schemas"]["LeagueVisibility"];
            settings: components["schemas"]["MarchMadnessSettings"];
        };
        MarchMadnessSettings: {
            /** @default 5 */
            maxBracketsPerMember: number;
            /** @enum {string} */
            scoringModel: "standard_doubling";
        } | {
            /** @default 5 */
            maxBracketsPerMember: number;
            /** @enum {string} */
            scoringModel: "custom";
            roundValues: number[];
        };
        MyLeaguesResponse: {
            leagues: components["schemas"]["LeagueSummary"][];
        };
        LeagueSummary: {
            id: string;
            name: components["schemas"]["LeagueName"];
            mode: components["schemas"]["LeagueMode"];
            visibility: components["schemas"]["LeagueVisibility"];
            status: components["schemas"]["LeagueStatus"];
            memberCount: number;
            myRole: components["schemas"]["MemberRole"];
            /** Format: date-time */
            startsAt: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server misconfiguration — structurally unreachable outside generate-openapi.ts, which builds the app with no deps and only ever requests the spec document, never invoking this handler. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted — profile anonymized, OAuth identities and sessions removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server misconfiguration — structurally unreachable outside generate-openapi.ts, which builds the app with no deps and only ever requests the spec document, never invoking this handler. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description No fields supplied, or a supplied field fails its format rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Username already taken by another user */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server misconfiguration — structurally unreachable outside generate-openapi.ts, which builds the app with no deps and only ever requests the spec document, never invoking this handler. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runNflSyncSchedule: {
        parameters: {
            query?: {
                season?: number;
                week?: number;
                weekType?: components["schemas"]["WeekType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job completed — counters in `details` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunResponse"];
                };
            };
            /** @description A supplied query param (season/week) fails its format rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or wrong x-job-secret header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job failed, or a dependency is not configured — same envelope either way */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunResponse"];
                };
            };
        };
    };
    runNflSyncOdds: {
        parameters: {
            query?: {
                season?: number;
                week?: number;
                weekType?: components["schemas"]["WeekType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job completed — counters in `details` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunResponse"];
                };
            };
            /** @description A supplied query param (season/week) fails its format rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or wrong x-job-secret header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job failed, or a dependency is not configured — same envelope either way */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunResponse"];
                };
            };
        };
    };
    runNflSyncScores: {
        parameters: {
            query?: {
                season?: number;
                week?: number;
                weekType?: components["schemas"]["WeekType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job completed — counters in `details` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunResponse"];
                };
            };
            /** @description A supplied query param (season/week) fails its format rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or wrong x-job-secret header */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job failed, or a dependency is not configured — same envelope either way */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunResponse"];
                };
            };
        };
    };
    listMyLeagues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's leagues, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyLeaguesResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server misconfiguration — structurally unreachable outside generate-openapi.ts, which builds the app with no deps and only ever requests the spec document, never invoking this handler. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createLeague: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateLeagueRequest"];
            };
        };
        responses: {
            /** @description League created in a pre-start state */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueResponse"];
                };
            };
            /** @description Invalid name, mode, visibility, or mode settings */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Creator is already commissioner of 10 active leagues (cap_exceeded), or the mode's sport has no ingested season to bind to (no_active_season) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server misconfiguration — structurally unreachable outside generate-openapi.ts, which builds the app with no deps and only ever requests the spec document, never invoking this handler. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLeague: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The league, its settings, and its members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueResponse"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such league, or the caller is not a member — indistinguishable so private leagues stay hidden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server misconfiguration — structurally unreachable outside generate-openapi.ts, which builds the app with no deps and only ever requests the spec document, never invoking this handler. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
