/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ClaimUsernameRouteImport } from './routes/claim-username'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedDiscoveryRouteImport } from './routes/_authed/discovery'
import { Route as AuthedGuideRouteImport } from './routes/_authed/guide'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedSimRouteRouteImport } from './routes/_authed/sim/route'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as RulesPickemRouteImport } from './routes/rules/pickem'
import { Route as RulesSimulatorRouteImport } from './routes/rules/simulator'
import { Route as RulesSurvivorRouteImport } from './routes/rules/survivor'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminGamesRouteImport } from './routes/_authed/admin/games'
import { Route as AuthedAdminStatsRouteImport } from './routes/_authed/admin/stats'
import { Route as AuthedAdminTeamsRouteImport } from './routes/_authed/admin/teams'
import { Route as AuthedLeaguesLeagueIdRouteRouteImport } from './routes/_authed/leagues/$leagueId/route'
import { Route as AuthedLeaguesNewRouteImport } from './routes/_authed/leagues/new'
import { Route as AuthedSimIndexRouteImport } from './routes/_authed/sim/index'
import { Route as AuthedSimFixturesRouteImport } from './routes/_authed/sim/fixtures'
import { Route as AuthedSimResetRouteImport } from './routes/_authed/sim/reset'
import { Route as AuthedSimScenariosRouteImport } from './routes/_authed/sim/scenarios'
import { Route as AuthedLeaguesLeagueIdIndexRouteImport } from './routes/_authed/leagues/$leagueId/index'
import { Route as AuthedLeaguesLeagueIdLeaguePicksRouteImport } from './routes/_authed/leagues/$leagueId/league-picks'
import { Route as AuthedLeaguesLeagueIdMembersRouteImport } from './routes/_authed/leagues/$leagueId/members'
import { Route as AuthedLeaguesLeagueIdMyPicksRouteImport } from './routes/_authed/leagues/$leagueId/my-picks'
import { Route as AuthedLeaguesLeagueIdSettingsRouteImport } from './routes/_authed/leagues/$leagueId/settings'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimUsernameRoute = ClaimUsernameRouteImport.update({
  id: '/claim-username',
  path: '/claim-username',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDiscoveryRoute = AuthedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGuideRoute = AuthedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSimRouteRoute = AuthedSimRouteRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => AuthedRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesPickemRoute = RulesPickemRouteImport.update({
  id: '/rules/pickem',
  path: '/rules/pickem',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesSimulatorRoute = RulesSimulatorRouteImport.update({
  id: '/rules/simulator',
  path: '/rules/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesSurvivorRoute = RulesSurvivorRouteImport.update({
  id: '/rules/survivor',
  path: '/rules/survivor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminGamesRoute = AuthedAdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminStatsRoute = AuthedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminTeamsRoute = AuthedAdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedLeaguesLeagueIdRouteRoute =
  AuthedLeaguesLeagueIdRouteRouteImport.update({
    id: '/leagues/$leagueId',
    path: '/leagues/$leagueId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLeaguesNewRoute = AuthedLeaguesNewRouteImport.update({
  id: '/leagues/new',
  path: '/leagues/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSimIndexRoute = AuthedSimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSimRouteRoute,
} as any)
const AuthedSimFixturesRoute = AuthedSimFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => AuthedSimRouteRoute,
} as any)
const AuthedSimResetRoute = AuthedSimResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthedSimRouteRoute,
} as any)
const AuthedSimScenariosRoute = AuthedSimScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AuthedSimRouteRoute,
} as any)
const AuthedLeaguesLeagueIdIndexRoute =
  AuthedLeaguesLeagueIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedLeaguesLeagueIdRouteRoute,
  } as any)
const AuthedLeaguesLeagueIdLeaguePicksRoute =
  AuthedLeaguesLeagueIdLeaguePicksRouteImport.update({
    id: '/league-picks',
    path: '/league-picks',
    getParentRoute: () => AuthedLeaguesLeagueIdRouteRoute,
  } as any)
const AuthedLeaguesLeagueIdMembersRoute =
  AuthedLeaguesLeagueIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedLeaguesLeagueIdRouteRoute,
  } as any)
const AuthedLeaguesLeagueIdMyPicksRoute =
  AuthedLeaguesLeagueIdMyPicksRouteImport.update({
    id: '/my-picks',
    path: '/my-picks',
    getParentRoute: () => AuthedLeaguesLeagueIdRouteRoute,
  } as any)
const AuthedLeaguesLeagueIdSettingsRoute =
  AuthedLeaguesLeagueIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedLeaguesLeagueIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/claim-username': typeof ClaimUsernameRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/sim': typeof AuthedSimRouteRouteWithChildren
  '/discovery': typeof AuthedDiscoveryRoute
  '/guide': typeof AuthedGuideRoute
  '/profile': typeof AuthedProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/rules/pickem': typeof RulesPickemRoute
  '/rules/simulator': typeof RulesSimulatorRoute
  '/rules/survivor': typeof RulesSurvivorRoute
  '/leagues/$leagueId': typeof AuthedLeaguesLeagueIdRouteRouteWithChildren
  '/admin/games': typeof AuthedAdminGamesRoute
  '/admin/stats': typeof AuthedAdminStatsRoute
  '/admin/teams': typeof AuthedAdminTeamsRoute
  '/leagues/new': typeof AuthedLeaguesNewRoute
  '/sim/fixtures': typeof AuthedSimFixturesRoute
  '/sim/reset': typeof AuthedSimResetRoute
  '/sim/scenarios': typeof AuthedSimScenariosRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/sim/': typeof AuthedSimIndexRoute
  '/leagues/$leagueId/league-picks': typeof AuthedLeaguesLeagueIdLeaguePicksRoute
  '/leagues/$leagueId/members': typeof AuthedLeaguesLeagueIdMembersRoute
  '/leagues/$leagueId/my-picks': typeof AuthedLeaguesLeagueIdMyPicksRoute
  '/leagues/$leagueId/settings': typeof AuthedLeaguesLeagueIdSettingsRoute
  '/leagues/$leagueId/': typeof AuthedLeaguesLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/claim-username': typeof ClaimUsernameRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/discovery': typeof AuthedDiscoveryRoute
  '/guide': typeof AuthedGuideRoute
  '/profile': typeof AuthedProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/rules/pickem': typeof RulesPickemRoute
  '/rules/simulator': typeof RulesSimulatorRoute
  '/rules/survivor': typeof RulesSurvivorRoute
  '/': typeof AuthedIndexRoute
  '/admin/games': typeof AuthedAdminGamesRoute
  '/admin/stats': typeof AuthedAdminStatsRoute
  '/admin/teams': typeof AuthedAdminTeamsRoute
  '/leagues/new': typeof AuthedLeaguesNewRoute
  '/sim/fixtures': typeof AuthedSimFixturesRoute
  '/sim/reset': typeof AuthedSimResetRoute
  '/sim/scenarios': typeof AuthedSimScenariosRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/sim': typeof AuthedSimIndexRoute
  '/leagues/$leagueId/league-picks': typeof AuthedLeaguesLeagueIdLeaguePicksRoute
  '/leagues/$leagueId/members': typeof AuthedLeaguesLeagueIdMembersRoute
  '/leagues/$leagueId/my-picks': typeof AuthedLeaguesLeagueIdMyPicksRoute
  '/leagues/$leagueId/settings': typeof AuthedLeaguesLeagueIdSettingsRoute
  '/leagues/$leagueId': typeof AuthedLeaguesLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/claim-username': typeof ClaimUsernameRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/sim': typeof AuthedSimRouteRouteWithChildren
  '/_authed/discovery': typeof AuthedDiscoveryRoute
  '/_authed/guide': typeof AuthedGuideRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/join/$code': typeof JoinCodeRoute
  '/rules/pickem': typeof RulesPickemRoute
  '/rules/simulator': typeof RulesSimulatorRoute
  '/rules/survivor': typeof RulesSurvivorRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/leagues/$leagueId': typeof AuthedLeaguesLeagueIdRouteRouteWithChildren
  '/_authed/admin/games': typeof AuthedAdminGamesRoute
  '/_authed/admin/stats': typeof AuthedAdminStatsRoute
  '/_authed/admin/teams': typeof AuthedAdminTeamsRoute
  '/_authed/leagues/new': typeof AuthedLeaguesNewRoute
  '/_authed/sim/fixtures': typeof AuthedSimFixturesRoute
  '/_authed/sim/reset': typeof AuthedSimResetRoute
  '/_authed/sim/scenarios': typeof AuthedSimScenariosRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/sim/': typeof AuthedSimIndexRoute
  '/_authed/leagues/$leagueId/league-picks': typeof AuthedLeaguesLeagueIdLeaguePicksRoute
  '/_authed/leagues/$leagueId/members': typeof AuthedLeaguesLeagueIdMembersRoute
  '/_authed/leagues/$leagueId/my-picks': typeof AuthedLeaguesLeagueIdMyPicksRoute
  '/_authed/leagues/$leagueId/settings': typeof AuthedLeaguesLeagueIdSettingsRoute
  '/_authed/leagues/$leagueId/': typeof AuthedLeaguesLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim-username'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/welcome'
    | '/admin'
    | '/sim'
    | '/discovery'
    | '/guide'
    | '/profile'
    | '/join/$code'
    | '/rules/pickem'
    | '/rules/simulator'
    | '/rules/survivor'
    | '/leagues/$leagueId'
    | '/admin/games'
    | '/admin/stats'
    | '/admin/teams'
    | '/leagues/new'
    | '/sim/fixtures'
    | '/sim/reset'
    | '/sim/scenarios'
    | '/admin/'
    | '/sim/'
    | '/leagues/$leagueId/league-picks'
    | '/leagues/$leagueId/members'
    | '/leagues/$leagueId/my-picks'
    | '/leagues/$leagueId/settings'
    | '/leagues/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/claim-username'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/welcome'
    | '/discovery'
    | '/guide'
    | '/profile'
    | '/join/$code'
    | '/rules/pickem'
    | '/rules/simulator'
    | '/rules/survivor'
    | '/'
    | '/admin/games'
    | '/admin/stats'
    | '/admin/teams'
    | '/leagues/new'
    | '/sim/fixtures'
    | '/sim/reset'
    | '/sim/scenarios'
    | '/admin'
    | '/sim'
    | '/leagues/$leagueId/league-picks'
    | '/leagues/$leagueId/members'
    | '/leagues/$leagueId/my-picks'
    | '/leagues/$leagueId/settings'
    | '/leagues/$leagueId'
  id:
    | '__root__'
    | '/_authed'
    | '/claim-username'
    | '/privacy'
    | '/sign-in'
    | '/terms'
    | '/welcome'
    | '/_authed/admin'
    | '/_authed/sim'
    | '/_authed/discovery'
    | '/_authed/guide'
    | '/_authed/profile'
    | '/join/$code'
    | '/rules/pickem'
    | '/rules/simulator'
    | '/rules/survivor'
    | '/_authed/'
    | '/_authed/leagues/$leagueId'
    | '/_authed/admin/games'
    | '/_authed/admin/stats'
    | '/_authed/admin/teams'
    | '/_authed/leagues/new'
    | '/_authed/sim/fixtures'
    | '/_authed/sim/reset'
    | '/_authed/sim/scenarios'
    | '/_authed/admin/'
    | '/_authed/sim/'
    | '/_authed/leagues/$leagueId/league-picks'
    | '/_authed/leagues/$leagueId/members'
    | '/_authed/leagues/$leagueId/my-picks'
    | '/_authed/leagues/$leagueId/settings'
    | '/_authed/leagues/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ClaimUsernameRoute: typeof ClaimUsernameRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  JoinCodeRoute: typeof JoinCodeRoute
  RulesPickemRoute: typeof RulesPickemRoute
  RulesSimulatorRoute: typeof RulesSimulatorRoute
  RulesSurvivorRoute: typeof RulesSurvivorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-username': {
      id: '/claim-username'
      path: '/claim-username'
      fullPath: '/claim-username'
      preLoaderRoute: typeof ClaimUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/discovery': {
      id: '/_authed/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthedDiscoveryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/guide': {
      id: '/_authed/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthedGuideRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sim': {
      id: '/_authed/sim'
      path: '/sim'
      fullPath: '/sim'
      preLoaderRoute: typeof AuthedSimRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/pickem': {
      id: '/rules/pickem'
      path: '/rules/pickem'
      fullPath: '/rules/pickem'
      preLoaderRoute: typeof RulesPickemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/simulator': {
      id: '/rules/simulator'
      path: '/rules/simulator'
      fullPath: '/rules/simulator'
      preLoaderRoute: typeof RulesSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/survivor': {
      id: '/rules/survivor'
      path: '/rules/survivor'
      fullPath: '/rules/survivor'
      preLoaderRoute: typeof RulesSurvivorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/games': {
      id: '/_authed/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AuthedAdminGamesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/stats': {
      id: '/_authed/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthedAdminStatsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/teams': {
      id: '/_authed/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AuthedAdminTeamsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/leagues/$leagueId': {
      id: '/_authed/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof AuthedLeaguesLeagueIdRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leagues/new': {
      id: '/_authed/leagues/new'
      path: '/leagues/new'
      fullPath: '/leagues/new'
      preLoaderRoute: typeof AuthedLeaguesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sim/': {
      id: '/_authed/sim/'
      path: '/'
      fullPath: '/sim/'
      preLoaderRoute: typeof AuthedSimIndexRouteImport
      parentRoute: typeof AuthedSimRouteRoute
    }
    '/_authed/sim/fixtures': {
      id: '/_authed/sim/fixtures'
      path: '/fixtures'
      fullPath: '/sim/fixtures'
      preLoaderRoute: typeof AuthedSimFixturesRouteImport
      parentRoute: typeof AuthedSimRouteRoute
    }
    '/_authed/sim/reset': {
      id: '/_authed/sim/reset'
      path: '/reset'
      fullPath: '/sim/reset'
      preLoaderRoute: typeof AuthedSimResetRouteImport
      parentRoute: typeof AuthedSimRouteRoute
    }
    '/_authed/sim/scenarios': {
      id: '/_authed/sim/scenarios'
      path: '/scenarios'
      fullPath: '/sim/scenarios'
      preLoaderRoute: typeof AuthedSimScenariosRouteImport
      parentRoute: typeof AuthedSimRouteRoute
    }
    '/_authed/leagues/$leagueId/': {
      id: '/_authed/leagues/$leagueId/'
      path: '/'
      fullPath: '/leagues/$leagueId/'
      preLoaderRoute: typeof AuthedLeaguesLeagueIdIndexRouteImport
      parentRoute: typeof AuthedLeaguesLeagueIdRouteRoute
    }
    '/_authed/leagues/$leagueId/league-picks': {
      id: '/_authed/leagues/$leagueId/league-picks'
      path: '/league-picks'
      fullPath: '/leagues/$leagueId/league-picks'
      preLoaderRoute: typeof AuthedLeaguesLeagueIdLeaguePicksRouteImport
      parentRoute: typeof AuthedLeaguesLeagueIdRouteRoute
    }
    '/_authed/leagues/$leagueId/members': {
      id: '/_authed/leagues/$leagueId/members'
      path: '/members'
      fullPath: '/leagues/$leagueId/members'
      preLoaderRoute: typeof AuthedLeaguesLeagueIdMembersRouteImport
      parentRoute: typeof AuthedLeaguesLeagueIdRouteRoute
    }
    '/_authed/leagues/$leagueId/my-picks': {
      id: '/_authed/leagues/$leagueId/my-picks'
      path: '/my-picks'
      fullPath: '/leagues/$leagueId/my-picks'
      preLoaderRoute: typeof AuthedLeaguesLeagueIdMyPicksRouteImport
      parentRoute: typeof AuthedLeaguesLeagueIdRouteRoute
    }
    '/_authed/leagues/$leagueId/settings': {
      id: '/_authed/leagues/$leagueId/settings'
      path: '/settings'
      fullPath: '/leagues/$leagueId/settings'
      preLoaderRoute: typeof AuthedLeaguesLeagueIdSettingsRouteImport
      parentRoute: typeof AuthedLeaguesLeagueIdRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminGamesRoute: typeof AuthedAdminGamesRoute
  AuthedAdminStatsRoute: typeof AuthedAdminStatsRoute
  AuthedAdminTeamsRoute: typeof AuthedAdminTeamsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminGamesRoute: AuthedAdminGamesRoute,
  AuthedAdminStatsRoute: AuthedAdminStatsRoute,
  AuthedAdminTeamsRoute: AuthedAdminTeamsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedSimRouteRouteChildren {
  AuthedSimFixturesRoute: typeof AuthedSimFixturesRoute
  AuthedSimResetRoute: typeof AuthedSimResetRoute
  AuthedSimScenariosRoute: typeof AuthedSimScenariosRoute
  AuthedSimIndexRoute: typeof AuthedSimIndexRoute
}

const AuthedSimRouteRouteChildren: AuthedSimRouteRouteChildren = {
  AuthedSimFixturesRoute: AuthedSimFixturesRoute,
  AuthedSimResetRoute: AuthedSimResetRoute,
  AuthedSimScenariosRoute: AuthedSimScenariosRoute,
  AuthedSimIndexRoute: AuthedSimIndexRoute,
}

const AuthedSimRouteRouteWithChildren = AuthedSimRouteRoute._addFileChildren(
  AuthedSimRouteRouteChildren,
)

interface AuthedLeaguesLeagueIdRouteRouteChildren {
  AuthedLeaguesLeagueIdLeaguePicksRoute: typeof AuthedLeaguesLeagueIdLeaguePicksRoute
  AuthedLeaguesLeagueIdMembersRoute: typeof AuthedLeaguesLeagueIdMembersRoute
  AuthedLeaguesLeagueIdMyPicksRoute: typeof AuthedLeaguesLeagueIdMyPicksRoute
  AuthedLeaguesLeagueIdSettingsRoute: typeof AuthedLeaguesLeagueIdSettingsRoute
  AuthedLeaguesLeagueIdIndexRoute: typeof AuthedLeaguesLeagueIdIndexRoute
}

const AuthedLeaguesLeagueIdRouteRouteChildren: AuthedLeaguesLeagueIdRouteRouteChildren =
  {
    AuthedLeaguesLeagueIdLeaguePicksRoute:
      AuthedLeaguesLeagueIdLeaguePicksRoute,
    AuthedLeaguesLeagueIdMembersRoute: AuthedLeaguesLeagueIdMembersRoute,
    AuthedLeaguesLeagueIdMyPicksRoute: AuthedLeaguesLeagueIdMyPicksRoute,
    AuthedLeaguesLeagueIdSettingsRoute: AuthedLeaguesLeagueIdSettingsRoute,
    AuthedLeaguesLeagueIdIndexRoute: AuthedLeaguesLeagueIdIndexRoute,
  }

const AuthedLeaguesLeagueIdRouteRouteWithChildren =
  AuthedLeaguesLeagueIdRouteRoute._addFileChildren(
    AuthedLeaguesLeagueIdRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedSimRouteRoute: typeof AuthedSimRouteRouteWithChildren
  AuthedDiscoveryRoute: typeof AuthedDiscoveryRoute
  AuthedGuideRoute: typeof AuthedGuideRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedLeaguesLeagueIdRouteRoute: typeof AuthedLeaguesLeagueIdRouteRouteWithChildren
  AuthedLeaguesNewRoute: typeof AuthedLeaguesNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedSimRouteRoute: AuthedSimRouteRouteWithChildren,
  AuthedDiscoveryRoute: AuthedDiscoveryRoute,
  AuthedGuideRoute: AuthedGuideRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedLeaguesLeagueIdRouteRoute: AuthedLeaguesLeagueIdRouteRouteWithChildren,
  AuthedLeaguesNewRoute: AuthedLeaguesNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ClaimUsernameRoute: ClaimUsernameRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  JoinCodeRoute: JoinCodeRoute,
  RulesPickemRoute: RulesPickemRoute,
  RulesSimulatorRoute: RulesSimulatorRoute,
  RulesSurvivorRoute: RulesSurvivorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
