#!/usr/bin/env bash
# Assembles .vercel/output/ (Build Output API v3) — Vercel runs this as the
# project's buildCommand (vercel.json); framework auto-detection is bypassed
# (docs/runbooks/environments.md §Vercel).
#
# The API bundle is ESM, but deps like pg are CJS and call require() for Node
# built-ins at runtime — the createRequire banner is what makes that work.
# Removing it builds fine and then crashes prod at cold start.
set -euo pipefail
cd "$(dirname "$0")/.."

rm -rf .vercel/output
mkdir -p .vercel/output/static

pnpm --filter @picksleagues/web build
cp -R apps/web/dist/. .vercel/output/static/

FUNC_DIR=.vercel/output/functions/api.func
mkdir -p "$FUNC_DIR"
pnpm exec esbuild apps/api/src/vercel.ts \
  --bundle \
  --platform=node \
  --format=esm \
  --target=node24 \
  --external:pg-native \
  --banner:js="import { createRequire } from 'node:module'; const require = createRequire(import.meta.url);" \
  --outfile="$FUNC_DIR/index.mjs"

# The SPA shell, beside the function: /join/<code> is served by the function so
# a pasted invite link unfurls with the league's name (ADR-0038), and what it
# returns is this exact document with four meta tags swapped — so a human
# following the link boots the same SPA, hashed asset URLs and all.
cp apps/web/dist/index.html "$FUNC_DIR/index.html"

cat > "$FUNC_DIR/.vc-config.json" <<'JSON'
{
  "runtime": "nodejs24.x",
  "handler": "index.mjs",
  "launcherType": "Nodejs",
  "shouldAddHelpers": false,
  "supportsResponseStreaming": true
}
JSON

# Route order: immutable-cache headers for hashed assets, then static files,
# then the prerendered public pages, then invite links and every /api path to
# the function (it owns its own 404s), then the SPA fallback for client routes.
#
# The prerendered rules are generated by the prerender (apps/web/prerender,
# LNCH-13) so a page added there can't ship unreachable. They sit after the
# filesystem handler, which may well resolve the same files by directory index
# first — these exist because the Build Output API docs never promise it, and
# the SPA fallback below would otherwise answer /welcome with the empty shell
# that got the app's OAuth branding rejected.
#
# `/join/<code>` goes to the function ahead of the SPA fallback so the link
# unfurls as an invitation instead of the generic app pitch (ADR-0038) — the
# function returns the same shell with its meta tags rewritten, so the human
# case is unchanged. Only the bare invite path: anything deeper still falls
# through to the SPA.
cat > .vercel/output/config.json <<'JSON'
{
  "version": 3,
  "routes": [
    {
      "src": "/assets/(.*)",
      "headers": { "cache-control": "public, max-age=31536000, immutable" },
      "continue": true
    },
    { "handle": "filesystem" },
JSON
cat apps/web/prerender/dist/vercel-routes.fragment >> .vercel/output/config.json
cat >> .vercel/output/config.json <<'JSON'
    { "src": "^/join/[^/]+/?$", "dest": "/api" },
    { "src": "^/api(?:/.*)?$", "dest": "/api" },
    { "src": "/(.*)", "dest": "/index.html" }
  ]
}
JSON

# The splice above is three concatenated pieces, so a malformed fragment would
# ship a config Vercel rejects at deploy time. Fail here instead.
node -e 'JSON.parse(require("node:fs").readFileSync(".vercel/output/config.json", "utf8"))'

echo "Build Output API assembly complete:"
find .vercel/output -maxdepth 3 -not -path '*/static/assets/*' | sort
